### ISSUE TITLE
What this error message means?

### ISSUE THREAD

**Issue by IptablesNat** [imperva/mx-toolbox#2]
[root@One user]# python get_gateway_stats.py 
Traceback (most recent call last):
  File "get_gateway_stats.py", line 491, in <module>
    run()
  File "get_gateway_stats.py", line 146, in run
    sendSyslog(GWStats)
  File "get_gateway_stats.py", line 488, in sendSyslog
    logging.warning("sendSyslog() exception: "+msg)
TypeError: cannot concatenate 'str' and 'error' objects
[root@One user]#

**Comment by IptablesNat** [comment]
I already know what caused this error message.Because the syslog server is not started.
