### ISSUE TITLE
IndexError: list index out of range statMeasurement

### ISSUE THREAD

**Issue by mihaiturcu** [imperva/mx-toolbox#6]
Hi,

I'm hitting the following error message when trying to run the gw script on one of our appliances.

[root@something user-data]# /usr/bin/python /var/user-data/get_gateway_stats.py
Traceback (most recent call last):
  File "/var/user-data/get_gateway_stats.py", line 734, in <module>
    run()
  File "/var/user-data/get_gateway_stats.py", line 190, in run
    getSysStats()
  File "/var/user-data/get_gateway_stats.py", line 408, in getSysStats
    statMeasurement = statAry[1][:5].replace(".","").strip()
IndexError: list index out of range

Do let me know if I should open a support case.

Thanks,
Mihai

**Comment by mihaiturcu** [comment]
so a print of str(statAry) returns ['somenumberhere+total']. It's basically a list with a single element so it won't be able to access the 2nd element, extract just for 5 chars, replace dots and all that :)

This is basically the only thing failing here. I can get around it but unsure what value this should be, in terms of relevance.

**Comment by mihaiturcu** [comment]
for curStat in statsAry:
                    statAry = curStat.strip().split()
                    if "total" in str(statAry):
                      statMeasurement = statAry[0].split('+')[0]
                    else:
                      statMeasurement = statAry[1][:5].replace(".","").strip()
                    if statMeasurement=="total" or statMeasurement=="used" or statMeasurement=="free":
                        sysStat.append(statType+"_"+statMeasurement+"="+statAry[0])
                        GWStats["top_"+statType+"_"+statMeasurement] = float(statAry[0])
                        GWSonarStats["memory"][statType][statMeasurement] = float(statAry[0])

ended up doing this for now
https://github.com/imperva/mx-toolbox/blob/master/performance-monitoring/get_gateway_stats.py
